#!/usr/bin/make -f

all:

install:
	install -D -m755 launch "$(DESTDIR)"/snap/command-chain/ros1-launch
	install -D -m755 roslaunch "$(DESTDIR)"/roslaunch
	install -D -m755 rosrun "$(DESTDIR)"/rosrun

.PHONY: all install
